### ISSUE TITLE
Debian ignores files with dot in name under /etc/cron.d

### ISSUE THREAD

**Issue by evilham** [debops/ansible-cron#3]
From `man cron`: 

> As described above, the files under these directories have to be pass some sanity checks including the following: be executable, be owned by root, not be writable by group or other and, if symlinks, point to files owned by
>        root. Additionally, the file names must conform to the filename requirements of run-parts: they must be entirely made up of letters, digits and can only contain the special signs underscores ('_') and  hyphens  ('-').  Any
>        file  that  does not conform to these requirements will not be executed by run-parts.  For example, any file containing dots will be ignored

I just spent quite a bit realising this :-p.

Would it be acceptable to add a an assertion that fails if the filename would result in it being ignored?

**Comment by drybjed** [comment]
Sure, sounds good. If you want, post a PR with it, otherwise it can be implemented after the roles are merged.

**Comment by evilham** [comment]
Of course, priorities :).

I'll prepare the PR at some point this week, just wanted to consult that before actually doing it; cheers!
