### ISSUE TITLE
Role is not found on galaxy

### ISSUE THREAD

**Issue by tterranigma** [debops/ansible-cron#4]
https://galaxy.ansible.com/debops does not list the role and the [direct link](https://galaxy.ansible.com/debops/cron) leads nowhere.

**Comment by drybjed** [comment]
The DebOps development has been focused in the [DebOps monorepo](https://github.com/debops/debops/), the separate role repositories are not supported anymore.

You should be able to [install DebOps using `mazer` from Ansible Galaxy](https://docs.debops.org/en/master/user-guide/install.html#installation-from-ansible-galaxy). This will install the entire monorepo as a "multi-repo", and the `debops.cron` role will be included in it. Check the linked documentation page for more information on how to use it without the entire DebOps setup.

**Comment by tterranigma** [comment]
Alright, thanks for the info. Should this repo be marked as archived?
